version: '3'

services:

  # todo volumes
  # todo better way to sync db schema from https://github.com/forbole/bdjuno/tree/chains/osmosis/database/schema
  postgres:
    image: postgres:latest
    container_name: osmosis-index-postgres
    restart: always
    volumes:
      - ./database/schema/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: osmosis-index-hasura
    restart: always
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    ports:
      - ${HASURA_PORT}:8080

  osjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "postgres"
    environment:
      OSJUNO_DATABASE_HOST: postgres
      OSJUNO_DATABASE_PORT: ${DB_PORT}
      OSJUNO_DATABASE_NAME: ${DB_NAME}
      OSJUNO_DATABASE_USER: ${DB_USER}
      OSJUNO_DATABASE_PASSWORD: ${DB_PASSWORD}
      OSJUNO_RPC_ADDRESS: ${OSMO_RPC_ADDRESS}
    volumes:
      - ~/.osjuno:/osjuno/.osjuno
